// ========================================================================
// FILE: scripts/check-docs.mjs
// PURPOSE: Guard docs consistency — flag orphan pages and broken internal links.
// DESCRIPTION: Runs after `astro build`. Fails (exit 1) if any published page is
//   not reachable from the sidebar (manual `slug` entry OR an `autogenerate`
//   directory OR intentionally `sidebar.hidden`), or if any internal markdown
//   link points at a route that was not built. Keeps the manual + autogenerated
//   sidebar honest as modules add pages.
// ========================================================================
import fs from 'fs';
import path from 'path';

const DOCS = 'src/content/docs';
const DIST = 'dist';
const CONFIG = 'astro.config.mjs';

const read = (f) => fs.readFileSync(f, 'utf8').replace(/\r\n/g, '\n');

// --- sidebar coverage from astro.config.mjs ---
const cfg = read(CONFIG);
const manualSlugs = new Set([...cfg.matchAll(/slug:\s*"([^"]+)"/g)].map((m) => m[1]));
const autoDirs = [...cfg.matchAll(/autogenerate:\s*\{\s*directory:\s*"([^"]+)"/g)].map((m) => m[1]);

function walk(dir) {
  let out = [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) out = out.concat(walk(p));
    else if (e.name.endsWith('.mdx') || e.name.endsWith('.md')) out.push(p);
  }
  return out;
}
const slugOf = (file) => {
  let rel = path.relative(DOCS, file).replace(/\\/g, '/').replace(/\.(mdx|md)$/, '');
  if (rel === 'index') return '';
  if (rel.endsWith('/index')) rel = rel.slice(0, -'/index'.length);
  return rel;
};
const isHidden = (file) => {
  const fm = read(file).match(/^---\n([\s\S]*?)\n---/);
  return fm ? /\bhidden:\s*true\b/.test(fm[1]) : false;
};
const coveredByAuto = (slug) => autoDirs.some((d) => slug === d || slug.startsWith(d + '/'));

const pages = walk(DOCS);
const orphans = [];
for (const f of pages) {
  const slug = slugOf(f);
  if (slug === '') continue; // root redirect
  if (manualSlugs.has(slug) || coveredByAuto(slug) || isHidden(f)) continue;
  orphans.push(slug);
}

// --- broken internal links (needs dist/) ---
let broken = [];
if (fs.existsSync(DIST)) {
  const routes = new Set();
  const collect = (dir, base = '') => {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      if (!e.isDirectory()) continue;
      const sub = path.join(dir, e.name);
      const rel = base + '/' + e.name;
      if (fs.existsSync(path.join(sub, 'index.html'))) routes.add(rel + '/');
      collect(sub, rel);
    }
  };
  collect(DIST);
  if (fs.existsSync(path.join(DIST, 'index.html'))) routes.add('/');
  const linkRe = /\]\((\/[^)\s]*)\)/g;
  for (const f of pages) {
    const txt = read(f);
    let m;
    while ((m = linkRe.exec(txt))) {
      let url = m[1];
      const h = url.indexOf('#');
      if (h >= 0) url = url.slice(0, h);
      if (url === '') continue;
      const norm = url.endsWith('/') ? url : url + '/';
      if (norm === '/' && routes.has('/')) continue;
      if (!routes.has(norm)) broken.push(`${path.relative('.', f)}  ->  ${m[1]}`);
    }
  }
} else {
  console.log('check-docs: dist/ not found — skipping link check (run after `astro build`).');
}

// --- report ---
let failed = false;
if (orphans.length) {
  failed = true;
  console.error(`\n✗ ${orphans.length} orphan page(s) — published but not in the sidebar (add to astro.config.mjs, put under an autogenerate dir, or mark sidebar.hidden):`);
  orphans.sort().forEach((s) => console.error('   /' + s + '/'));
}
if (broken.length) {
  failed = true;
  console.error(`\n✗ ${broken.length} broken internal link(s):`);
  broken.forEach((b) => console.error('   ' + b));
}
if (!failed) {
  console.log(`check-docs: OK — ${pages.length} pages, 0 orphans, 0 broken internal links (${manualSlugs.size} manual slugs, ${autoDirs.length} autogenerate dirs).`);
} else {
  console.error('\ncheck-docs: FAILED — fix the above before deploying.\n');
  process.exit(1);
}
